In [1]:
%config Completer.use_jedi = False                                       
import warnings                                                             
warnings.filterwarnings(action="ignore")
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


<img src="./딥러닝 (2).png">
<img src="./딥러닝 (1).png">

<img src="./퍼셉트론 (2).png">
<img src="./퍼셉트론 (1).png">
<img src="./퍼셉트론 (3).png">

***
퍼셉트론은 엄밀히 말하면 딥러닝은 아니지만 뉴런과 상당히 닮은 분류기이다.  
뉴런의 계산과정을 이해하고 뉴런 하나만으로 AND, OR 연산과 같은 기초적인 연산을 할 수 있음을 알아본다.
***

In [2]:
# 퍼셉트론 코드의 이해도를 높이기 위해 1을 True로, 0을 False로 그리고 편향(bias)은 1로 지정한다.
T = 1.0
F = 0.0
bias = 1.0

***
AND, OR, XOR 실습 데이터를 함수로 정의해 함수를 호출하면 데이터를 얻을 수 있게 한다.
***

In [3]:
def get_AND_data():
    #학습 데이터
    X = [
         [F, F, bias], # F
         [F, T, bias], # F
         [T, F, bias], # F
         [T, T, bias]  # T
    ]
    # 학습 데이터에 따른 실제값(레이블, 타겟, 클래스)
    Y = [
        [F],
        [F],
        [F],
        [T],
    ]
    return X, Y

def get_OR_data():
    #학습 데이터
    X = [
         [F, F, bias], # F
         [F, T, bias], # F
         [T, F, bias], # T
         [T, T, bias]  # T
    ]
    # 학습 데이터에 따른 실제값(레이블, 타겟, 클래스)
    Y = [
        [F],
        [T],
        [T],
        [T],
    ]
    return X, Y



def get_XOR_data():
    #학습 데이터
    X = [
         [F, F, bias], # F
         [F, T, bias], # T
         [T, F, bias], # T
         [T, T, bias]  # F
    ]
    # 학습 데이터에 따른 실제값(레이블, 타겟, 클래스)
    Y = [
        [F],
        [T],
        [T],
        [F],
    ]
    return X, Y



In [4]:
# AND 연산에 필요한 데이터를 호출한다.
#X, Y = get_AND_data()
# OR 연산에 필요한 데이터를 호출한다.
X, Y = get_OR_data()
# XOR 연산에 필요한 데이터를 호출한다.
#X, Y = get_XOR_data()
print(X, Y)

[[0.0, 0.0, 1.0], [0.0, 1.0, 1.0], [1.0, 0.0, 1.0], [1.0, 1.0, 1.0]] [[0.0], [1.0], [1.0], [1.0]]


***
tenserflow를 사용해서 퍼셉트론을 구현한다.
***

In [5]:
# 논리 연산을 위한 입력값으로 X, Y, 편향값을 입력받아(총 3개의 입력) 1개의 값을 출력해야 하므로 가중치는 [3, 1]로 설정한다.
# matmul() 메소드로 행렬의 내적을 실행하기 위해 입력 데이터가 1행 3열이므로 가중치를 3행 1열로 만든다.
#W = tf.Variable(tf.random_normal( (3, 1) )) # 정규분포를 따르는 난수를 만든다.
W = tf.Variable(tf.random_uniform( (3, 1) )) # 균등분포를 따르는 난수를 만든다.
sess = tf.Session() # 세션을 만든다.
sess.run(tf.global_variables_initializer()) # 변수를 초기화한다. 
print(sess.run(W))

[[0.7616297 ]
 [0.48673058]
 [0.1578517 ]]


***
퍼셉트론은 두 개의 입력이 있을 때 하나의 뉴런으로 두 개의 입력을 계산한 뒤 최종적으로 0 또는 1을 출력한다.  
두 개의 입력은 가중치와 곱해져 뉴런의 첫번째 단계인 시그마로 들어가고,  
시그마 단계에서 모든 가중치와 입력값을 곱한 결과에 편향값을 더하는 과정이 이룯어진다.

시그마 값은 뉴런의 두번째 단계인 활성화 함수의 입력으로 들어가는데 퍼셉스톤은 스텝 함수라는 활성화 함수를 사용하고,  
스텝 함수는 시그마값이 x <= 0 일 경우 0을, x > 0일 경우 1을 출력한다.
***

In [6]:
sess = tf.Session()
# tensorflow의 greater(a, b) 메소드는 a > b일 경우 True, 그렇지 않으면 False
#print(sess.run( tf.greater(1, 0) ))
# tensorflow의 greater_equal(a, b) 메소드는 a >= b일 경우 True, 그렇지 않으면 False
#print(sess.run( tf.greater_equal(1, 0) ))
# tensorflow의 less(a, b) 메소드는 a < b일 경우 True, 그렇지 않으면 False
#print(sess.run( tf.less(1, 0) ))
# tensorflow의 less_equal(a, b) 메소드는 a <= b일 경우 True, 그렇지 않으면 False
#print(sess.run( tf.less_equal(1, 0) ))
# tensorflow의 equal(a, b) 메소드는 a = b일 경우 True, 그렇지 않으면 False
#print(sess.run( tf.equal(1, 0) ))
# tensorflow의 not_equal(a, b) 메소드는 a != b일 경우 True, 그렇지 않으면 False
#print(sess.run( tf.not_equal(1, 0) ))

print(sess.run( tf.greater(1, 0) ))
# tensorflow의 cast(데이터, dtype) 메소드는 데이터를 dtype으로 형변환한다.
# True는 숫자로 형변환하면 1, False는 숫자로 형변환하면 0으로 변환된다.
f = tf.cast( tf.greater(1, 0), dtype=tf.float32 )
print(sess.run(f))

print(sess.run( tf.greater(1, 1) ))
f = tf.cast( tf.greater(1, 1), dtype=tf.float32 )
print(sess.run(f))

True
1.0
False
0.0


In [7]:
# x가 0보다 크면 1, x가 0이하이면 0을 리턴하는 활성화 함수를 구현한다.
def step(z):
    return tf.cast( tf.greater(z, 0), dtype=tf.float32 )

In [8]:
# 손실(오차, 비용) 함수로 평균 제곱 오차(MSE)를 사용한다.
sess = tf.Session() # 세션을 만든다.
sess.run(tf.global_variables_initializer()) # 변수를 초기화한다. 

# 행렬의 내적 메소드로 학습 데이터(X)와 가중치(W)를 곱한다.
z = tf.matmul(X, W)
print('예측값\n', sess.run(z))
print('-' * 100)

# 예측값을 활성화(스텝) 함수에 넣어 최종 예측값을 계산한다.
output = step(z)
print('최종 예측값\n', sess.run(output))
print('-' * 100)

# 레이블(Y)과 최종 예측값(스텝 함수 실행 결과; output)의 편차를 계산한다.
error = tf.subtract(Y, output)
print('레이블(Y)과 최종 예측값(output)의 편차\n', sess.run(error))
print('-' * 100)

# 평균 제곱 오차를 계산한다.
mse = tf.reduce_mean( tf.square(error) )
print('평균 제곱 오차\n', sess.run(mse))

예측값
 [[0.17539155]
 [0.21257651]
 [0.7898325 ]
 [0.8270174 ]]
----------------------------------------------------------------------------------------------------
최종 예측값
 [[1.]
 [1.]
 [1.]
 [1.]]
----------------------------------------------------------------------------------------------------
레이블(Y)과 최종 예측값(output)의 편차
 [[-1.]
 [ 0.]
 [ 0.]
 [ 0.]]
----------------------------------------------------------------------------------------------------
평균 제곱 오차
 0.25


***
보통의 경우 딥러닝 모델은 경사 하강법을 통해 매개 변수를 최적화하지만  
미분값이 큰 의미가 없는 스텝 함수의 영향으로(0은 미분 불가능, 1(상수)은 미분하면 1) 퍼셉트론은 아래와 같은 방법으로 최적화를 진행한다.  
***

***
퍼셉트론의 오차
***
결과값이 1이 나와야하는데 스텝함수의 출력이 0인 경우 : w_new = w_origin + delta (w_origin; 기존 가중치)   
결과값이 0이 나와야하는데 스텝함수의 출력이 1인 경우 : w_new = w_origin - delta  

위의 2가지 경우를 다음과 같이 사용할 수 있다.

In [9]:
import numpy as np

In [10]:
print(type(X))
print(type( np.array(X) ))
print( np.array(X) )
print( np.array(X).T ) # 전치

<class 'list'>
<class 'numpy.ndarray'>
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
[[0. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 1.]]


In [11]:
#행렬의 transpose는 행과 열을 교환하여 얻는 전치행렬를 의미한다.
#matmul(A, B, transpose_a=True)는 행렬을 내적하기 전에 A행렬을 전치하고 내적한다.
#matmul(A, B, transpose_b=True)는 행렬을 내적하기 전에 B행렬을 전치하고 내적한다.
sess = tf.Session()
sess.run(tf.global_variables_initializer())
delta = tf.matmul(X, error, transpose_a=True) #행렬의 내적을 계산하기 전에 행렬 X를 전치한다.
print('가중치를 수정할 값\n', sess.run(delta))
print('------------------------------------')

# 가중치를 가중치를 수정할 값으로 수정해서 다시 계산한다. -> 역전파
print('수정된 가중치\n', sess.run(tf.add(W, delta)))
print('------------------------------------')

#assign() 메소드는 세션안에서 tensorflow 변수 값을 수정한다.
train = tf.assign( W, tf.add(W, delta) )

가중치를 수정할 값
 [[ 0.]
 [ 0.]
 [-1.]]
------------------------------------
수정된 가중치
 [[ 0.2688514 ]
 [ 0.9247898 ]
 [-0.15957189]]
------------------------------------


***
학습 후 테스트
***

In [12]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

err, epoch, max_epoch = 1.0, 0, 20 # 오차, 현재 학습 횟수, 최대 학습 횟수
# 오차가 발생하고 학습 횟수가 최대 학습 횟수를 초과하지 않는 동안 반복한다.
while err > 0.0 and epoch < max_epoch : 
    epoch += 1 # 학습 횟수를 증가시킨다.
    err = sess.run(mse) # 평균 제곱 오차를 계산한다. 
    sess.run(train) # 학습시킨다.
    print('epoch -> {:2d}, mse -> {}'.format(epoch, err))
#------- while

print('학습 결과\n', sess.run(output))
sess.close()

epoch ->  1, mse -> 0.25
epoch ->  2, mse -> 0.0
학습 결과
 [[0.]
 [1.]
 [1.]
 [1.]]


In [13]:
# 세션을 with구문을 사용해서 만들면 with 블록이 종료되는 순간 자동으로 close한다.
with tf.Session() as sess: # 세션을 만든다.
    sess.run(tf.global_variables_initializer())

    err, epoch, max_epoch = 1.0, 0, 20 
    while err > 0.0 and epoch < max_epoch : 
        epoch += 1
        err = sess.run(mse)
        sess.run(train)
        print('epoch -> {:2d}, mse -> {}'.format(epoch, err))
    #------- while

    print('학습 결과\n', sess.run(output))


epoch ->  1, mse -> 0.25
epoch ->  2, mse -> 0.25
epoch ->  3, mse -> 0.25
epoch ->  4, mse -> 0.0
학습 결과
 [[0.]
 [1.]
 [1.]
 [1.]]
